name: Release Tag Package
description: This action creates a release tag and uploads the package to the release.

inputs:
  package_json_path:
    description: 'the path to the package.json file to read the version from'
    required: false
    default: './package.json'
  github_token:
    description: 'GitHub token with permissions to create releases.'
    required: true
  release_branch_name:
    description: 'the name of the branch create a release from'
    required: false

runs:
  using: 'composite'
  steps:

  - name: Get version from package.json
    id: package
    shell: bash
    run: |
      version=$(node -p "require('${{ inputs.package_json_path }}').version")
      echo "version from package json: $version"
      echo "version=$version" >> $GITHUB_OUTPUT

  - name: 'Check if tag already exists'
    id: check_tag
    shell: bash
    run: |
      if gh release view ${{ steps.package.outputs.version }} > /dev/null 2>&1; then
        echo "Tag ${{ steps.package.outputs.version }} already exists. Skipping creation."
        echo "tag_exists=true" >> $GITHUB_OUTPUT
      else
        echo "Tag ${{ steps.package.outputs.version }} does not exist."
        echo "tag_exists=false" >> $GITHUB_OUTPUT
      fi
    env:
      GH_TOKEN: ${{ github.token }}

  - name: Create Release Tag
    if: steps.check_tag.outputs.tag_exists == 'false'
    id: release_tag
    shell: bash
    run: |
      trailing_text="${{ inputs.release_branch_name && format('deployed from {0} branch', inputs['release_branch_name'] || github.ref_name) }}"
      echo "text=$trailing_text" >> $GITHUB_OUTPUT
      echo "Creating release tag: ${{ steps.package.outputs.version }} $trailing_text"

      gh release create ${{ steps.package.outputs.version }} \
        --title "${{ steps.package.outputs.version }}" \
        --target ${{ inputs.release_branch_name || github.ref_name }}
    env:
      GH_TOKEN: ${{ github.token }}

  - name: Generate GitHub Summary
    shell: bash
    run: |
      echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
      echo "Release ${{ steps.package.outputs.version }} created successfully ${{ steps.release_tag.outputs.text }}." >> $GITHUB_STEP_SUMMARY
